version: '3.3'
services:
  db:
    image: postgres:14.5
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pet_clinic
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./dump:/docker-entrypoint-initdb.d

